site_name: SCC Wits1 Project
nav:
  - Home: index.md
  - "Week 1": week1.md
  - "Week 2": week2.md
  - "Week 3": week3.md
  - "Week 4": week4.md
  - "Week 5": week5.md
  - "Week 6": week6.md
theme: readthedocs
watch:
  - docs/
  - mkdocs.yml
